# Generated by Django 4.2.8 on 2025-05-27 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.FloatField(choices=[(2.0, '2'), (3.0, '3'), (4.0, '4'), (5.0, '5')], validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
